### ISSUE TITLE
Fix exception running our adapted metrics_config_ui.py

### ISSUE THREAD

**Issue by mbamba** [SocialSim/socialsim#11]
```
python metrics_config_ui.py -s /home/Public/socialsim/pnnl/sims_dryrun2/dryrun2_rDnnAndTempPref.csv -g /home/Public/socialsim/weekly_evals/groundtruth/new_groundtruth_time-events-20170701-20170831.csv -o eval_dryrun2_rDnnAndTempPref.log
```

**Comment by mbamba** [comment]
`Traceback (most recent call last):
  File "metrics_config_ui.py", line 724, in <module>
    main()
  File "metrics_config_ui.py", line 690, in main
    engine.evaluate(args.json_output_file)
  File "metrics_config_ui.py", line 664, in evaluate
    metrics = run_all_metrics(self.ground_truth, self.simulation)
  File "metrics_config_ui.py", line 603, in run_all_metrics
    gt, sim, metric_results = run_metrics(ground_truth, simulation, measurement_name)
  File "metrics_config_ui.py", line 524, in run_metrics
    measurement_function = getattr(ground_truth,p['measurement'])
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'computeTEUsers'
`
